### ISSUE TITLE
자동으로 로그아웃 안 되는 문제

### ISSUE THREAD

**Issue by zxcv859500** [alps-jbnu/litmus-site#20]
로그아웃 안하고 브라우저를 종료하면 여러 사람이 돌아가면서 쓰는 컴퓨터실 특성 상 개인정보가 노출될 가능성이 높으므로 수정 요망

**Comment by joonas-yoon** [comment]
로그아웃 안하는 것 까진 우리가 고려할 일이 아니라고 봄. 

세션 길이는 있어야하는 것 같은데, 로그인 세션 유지 시간은 얼마로 하는 게 나을까?

**Comment by zxcv859500** [comment]
보통 수업시간이 한 시간이니까 50분 정도로 맞추는게 좋을 것 같은데요?

**Comment by joonas-yoon** [comment]
#21
