### ISSUE TITLE
에디터 변경

### ISSUE THREAD

**Issue by joonas-yoon** [alps-jbnu/litmus-site#22]
지금은 markdown 에디터로 작성되고 있는 데, WYSIWYG 에디터인 [summernote](https://summernote.org/)로 바꾸는 건 어떨까 싶네요.

django의 위젯으로도 있는 것 같고, (https://github.com/summernote/django-summernote) 무료이지만 기존에 작성된 글들을 전부 WYSIWYG에 맞게 수정해야 하는 큰 산이 생기겠군요.

수식(MathJax) 작성 지원도 되기는 합니다. (https://github.com/thisroot/summernote-equation-plugin)

참고로 [트게더](https://tgd.kr/)에서 이 에디터를 사용하고 있습니다.

**Comment by wkdaudfo** [comment]
markdown 에디터보다 summernote 에디터가 좋은 점은 뭔가요?

**Comment by joonas-yoon** [comment]
(이지윅)[https://ko.wikipedia.org/wiki/%EC%9C%84%EC%A7%80%EC%9C%84%EA%B7%B8]에 대해서 먼저 알아보는 게 좋을 거 같습니다.

**Comment by joonas-yoon** [comment]
[이지윅](https://ko.wikipedia.org/wiki/%EC%9C%84%EC%A7%80%EC%9C%84%EA%B7%B8)에 대해서 먼저 알아보세요.

**Comment by joonas-yoon** [comment]
https://github.com/alps-jbnu/litmus-site/commit/8d4133bda73ddbe6e8aec40818f59bad89b37430
https://github.com/alps-jbnu/litmus-site/commit/c7f99d6501fc283ac02694b56d076dd2d5b98eb9
https://github.com/alps-jbnu/litmus-site/commit/1d37fd5b391f1d90c1efda92b3f6e5fdc01ec1c2
https://github.com/alps-jbnu/litmus-site/commit/46fdb968d6c5d06fd3ae2cd6b5bbd6feea44d1b0#diff-54d6e273cf7c50350f641b0855bb08e2R55
https://github.com/alps-jbnu/litmus-site/commit/c0a1f2a515cf34c875096ee61dff01218a0cd253
https://github.com/alps-jbnu/litmus-site/commit/fa71e4e79d2d3f174e2e07f321644437daee5b79
https://github.com/alps-jbnu/litmus-site/commit/f5f5b1992a68459e1e3a0ade6a22a9fd488b248c
https://github.com/alps-jbnu/litmus-site/commit/d6dbb04ba0cb4b03b5b3f7c0a854ed3e1bc43f4d
https://github.com/alps-jbnu/litmus-site/commit/2a94909b0f76a2f0eab3a967e9de1ee17fe5d6c2
