### ISSUE TITLE
문제를 만들 때 수정권한을 주는 것이 불편함

### ISSUE THREAD

**Issue by wkdaudfo** [alps-jbnu/litmus-site#24]
만든 사람 자신은 기본적으로 포함되어야하는데 그런 것이 없어서 만들고 나서 '아차' 할 수 있음.

**Comment by joonas-yoon** [comment]
소속을 추가할때도 같은 상황이 있네요.
등록자(Registrant)와 관리자(Administrators)도 추가화면에서는 기본값으로 자신으로 지정되도록 수정이 필요해보임
