### ISSUE TITLE
대회를 만든 사람 본인이 대회를 삭제할 수 없는 문제

### ISSUE THREAD

**Issue by zxcv859500** [alps-jbnu/litmus-site#28]
공개한 접근 코드를 이용하여 참가하는 대회에서 대회를 만든 교수가 대회를 삭제할 수 없음.

**Comment by joonas-yoon** [comment]
참가자가 없는 경우는 가능하고, 그렇지 않은 경우는 무결성때문에 일부러 막은 겁니다. 

아래의 메시지를 확인했다면 무결성의 이유가 맞습니다. 
```
contest를 삭제할 수 없습니다.
contest "xxx" 을/를 삭제하면서관련 오브젝트를 제거하고자 했으나, 지금 사용하시는 계정은 다음 타입의 오브젝트를 제거할 권한이 없습니다. :
 - 대회 참가자
```

**Comment by joonas-yoon** [comment]
관련된 권한들 이름:
- judge | 대회 참가자 | Can add contest participation
- judge | 대회 참가자 | Can change contest participation
- judge | 대회 참가자 | Can delete contest participation

[Link](https://github.com/alps-jbnu/litmus-site/wiki/%EA%B4%80%EB%A6%AC%EC%9E%90-%EA%B6%8C%ED%95%9C-%EC%84%A4%EB%AA%85)
