### ISSUE TITLE
Admin 페이지의 대회 접근 코드 입력 텍스트의 위치

### ISSUE THREAD

**Issue by zxcv859500** [alps-jbnu/litmus-site#29]
대회 코드라는 비슷한 이름의 입력 텍스트가 있고 접근 코드 입력 테스트는 너무 아래있으며 자동으로 입력되어 있어서 불편함이 따름

**Comment by zxcv859500** [comment]
접근 코드 옆에 버튼을 만들어 자동으로 값이 입력되게 하고 접근 코드 입력 텍스트를 위로 올리게 하도록 하는게 좋을 것 같다.

**Comment by joonas-yoon** [comment]
접근 코드 옆에 생성 버튼을 추가함: https://github.com/alps-jbnu/litmus-site/commit/5c3fbd451244f076a762589bd6f65fd0414bd2ae

**Comment by joonas-yoon** [comment]
대회 설명 작성을 아래로 내려서 접근 소속 및 코드 설정이 보다 위에 있도록 배치 변경:
https://github.com/alps-jbnu/litmus-site/commit/32b7fd40d1697b57eb685021c7050c3dab2e02c7
