### ISSUE TITLE
채점 중 페이지가 갱신되지 않음

### ISSUE THREAD

**Issue by zxcv859500** [alps-jbnu/litmus-site#30]
채점 중일 때 새로고침을 눌러야만 채점 결과가 나오는 현상이 있음.

주기적으로 새로고침을 자동으로 해주는 식으로 해결해야 될 듯함.

**Comment by joonas-yoon** [comment]
비동기 호출로 해결할 수 있는 지 알아보자

**Comment by joonas-yoon** [comment]
[configuration-of-event-server](https://dmoj.readthedocs.io/en/latest/site/installation/#configuration-of-event-server)에서 event server를 연결하면 judge와 웹 소켓을 통해 동적으로 갱신된다.

이벤트 서버 설정과 함께 `BRIDGED_DJANGO_ADDRESS`도 주석을 해제해야 한다.

**Comment by joonas-yoon** [comment]
https://github.com/alps-jbnu/litmus-site/commit/a40ab9eb7ecd2d4d499482d9c1577433cb2d54cc
