### ISSUE TITLE
pip 의존성 설치 중 문제 발생.

### ISSUE THREAD

**Issue by zxcv859500** [alps-jbnu/litmus-site#62]
![image](https://user-images.githubusercontent.com/19997493/70854340-ae6a9080-1efd-11ea-8ba7-2ccdbb4bab6b.png)

`pip install -r requirements.txt `

명령어로 의존성 설치 중에 위와 같은 에러가 발생했습니다.

vmware player로 ubuntu 16.04 LTS 에서 실행 중에 발생했습니다.

혹 해결 방법이 있으면 답변 부탁드립니다.

**Comment by zxcv859500** [comment]
mysqlclient 설치 관련 문제는 sudo apt-get install libssl-dev 로 해결했습니다.

**Comment by joonas-yoon** [comment]
ssl 패키지를 설치했는데 mysql 설치 오류가 해결된게 이상하네요. 그럼 이 이슈는 해결된건가요?

**Comment by zxcv859500** [comment]
네 해결되었습니다. 이슈 닫겠습니다.

**Comment by zxcv859500** [comment]
이 문제를 위키의 자주 발생하는 오류에 올려놓았습니다.
